objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>today()+14</defaultValue>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget_hrs__c</fullName>
        <label>Budget (hrs)</label>
        <summarizedField>Project_Budget__c.Selected_Budget_hrs__c</summarizedField>
        <summaryForeignKey>Project_Budget__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget_hrs_weekday__c</fullName>
        <formula>Budget_hrs__c /  Duration_weekdays__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget (hrs/weekday)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Project_Budget__c.object
<CustomObject>
    <label>Project Budget</label>
    <nameField>
        <displayFormat>PBU-{00000000}</displayFormat>
        <label>Project Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Opportunity Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Budget_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Budget_hrs__c</fullName>
        <formula>CASE(
    Type__c,
    &quot;Manual&quot;, Manual_Budget_hrs__c,
    &quot;Opportunity&quot;, Opportunity_Quantity_hrs__c,
    &quot;Opportunity Product&quot;, Opportunity_Product_Quantity_hrs__c,
    0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget_hrs_weekday__c</fullName>
        <formula>Budget_hrs__c /  Project__r.Duration_weekdays__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget (hrs/weekday)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Project_Budget_Rollup__c.object
<CustomObject>
    <label>Project Budget Rollup</label>
    <nameField>
        <displayFormat>PRR-{00000000}</displayFormat>
        <label>Project Budget Rollup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Budget Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <referenceTo>Time__c</referenceTo>
        <relationshipLabel>Project Budget Rollups</relationshipLabel>
        <relationshipName>Project_Budget_Rollups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Budget_hrs__c</fullName>
        <label>Budget (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Budget__c</fullName>
        <label>Project Budget</label>
        <referenceTo>Project_Budget__c</referenceTo>
        <relationshipLabel>Project Budget Rollups</relationshipLabel>
        <relationshipName>Project_Budget_Rollups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Project_Resource__c.object
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>PRS-{00000000}</displayFormat>
        <label>Project Resource</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Resources</relationshipLabel>
        <relationshipName>Project_Resource_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_hrs__c</fullName>
        <formula>Planned_hrs_Rollup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Planned (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_hrs_weekday__c</fullName>
        <formula>Default_FTE_weekday__c * 8</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Default (hrs/weekday)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Project_Role__c.object
<CustomObject>
    <label>Project Role</label>
    <nameField>
        <displayFormat>PRR-{00000000}</displayFormat>
        <label>Project Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Roles</relationshipLabel>
        <relationshipName>Project_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_hrs__c</fullName>
        <label>Planned (hrs)</label>
        <summarizedField>Project_Role_Rollup__c.Planned_hrs__c</summarizedField>
        <summaryForeignKey>Project_Role_Rollup__c.Project_Role__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Default_hrs_weekday__c</fullName>
        <formula>Default_FTE_weekday__c * 8</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Default (hrs/weekday)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Project_Role_Rollup__c.object
<CustomObject>
    <label>Project Role Rollup</label>
    <nameField>
        <displayFormat>PRR-{00000000}</displayFormat>
        <label>Project Role Rollup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Role Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <referenceTo>Time__c</referenceTo>
        <relationshipName>Project_Role_Rollups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_hrs__c</fullName>
        <label>Planned (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Role__c</fullName>
        <label>Project Role</label>
        <referenceTo>Project_Role__c</referenceTo>
        <relationshipName>Project_Roll_Rollups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Project_Task__c.object
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planned_hrs__c</fullName>
        <label>Planned (hrs)</label>
        <summarizedField>Project_Task_Rollup__c.Planned_hrs__c</summarizedField>
        <summaryForeignKey>Project_Task_Rollup__c.Project_Task__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Default_hrs_weekday__c</fullName>
        <formula>Default_FTE_weekday__c * 8</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Default (hrs/weekday)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Time__c.object
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TME-{00000000}</displayFormat>
        <label>Time</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PM_Time_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PM_Time_Categories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Budget_hrs__c</fullName>
        <label>Budget (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_hrs__c</fullName>
        <label>Planned (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Role</label>
        <referenceTo>Project_Role__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task</label>
        <referenceTo>Project_Task__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Budget</label>
        <referenceTo>Project_Budget__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Resource</label>
        <referenceTo>Project_Resource__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

globalValueSets/PM_Time_Categories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Project Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Project Role</fullName>
    </customValue>
    <customValue>
        <fullName>Project Resource</fullName>
    </customValue>
    <customValue>
        <fullName>Project Task</fullName>
    </customValue>
    <masterLabel>PM Time Categories</masterLabel>
</GlobalValueSet>

globalValueSets/PM_Time_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Available</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Planned</fullName>
    </customValue>
    <customValue>
        <fullName>Billable</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Billable</fullName>
    </customValue>
    <masterLabel>PM Time Types</masterLabel>
</GlobalValueSet>

classes/TimeHelper.cls
public class TimeHelper {

    // Method to create Time records for Project Budget
    public static void createTimeBudget(Project_Budget__c budget) {
        Id projectId = budget.Project__c;
        Project__c project = [SELECT Start_Date__c, End_Date__c FROM Project__c WHERE Id = :projectId LIMIT 1];
        
        List<Time__c> timesToCreate = new List<Time__c>();

        for (Date dateIter = project.Start_Date__c; dateIter <= project.End_Date__c; dateIter = dateIter.addDays(1)) {
            Decimal budgetHours = isWeekend(dateIter) ? null : budget.Budget_hrs_weekday__c;

            Time__c newTime = new Time__c();
            newTime.Project_Budget__c = budget.Id;
            newTime.Project__c = projectId;
            newTime.Date__c = dateIter;
            newTime.Budget_hrs__c = budgetHours;
            newTime.Type__c = 'Budget';
            newTime.Category__c = 'Project Budget';
            newTime.Key__c = generateKey(newTime);

            timesToCreate.add(newTime);
        }

        if (!timesToCreate.isEmpty()) {
            insert timesToCreate;
            createProjectBudgetRollups(budget, timesToCreate);
        }
    }

    // Method to update Time records for Project Budget when Budget or Budget_dphr__c changes
    public static void updateTimeBudget(Project_Budget__c budget) {
        List<Time__c> existingTimes = [SELECT Id, Date__c, Budget_hrs__c 
                                       FROM Time__c 
                                       WHERE Project_Budget__c = :budget.Id];

        List<Time__c> timesToUpdate = new List<Time__c>();

        for (Time__c timeRecord : existingTimes) {
            Decimal budgetHours = isWeekend(timeRecord.Date__c) ? null : budget.Budget_hrs_weekday__c;
            timeRecord.Budget_hrs__c = budgetHours;
            timesToUpdate.add(timeRecord);
        }

        if (!timesToUpdate.isEmpty()) {
            update timesToUpdate;
        }
    }

    // Method to delete Time records associated with a Project Budget
    public static void deleteTimesForProjectBudget(Project_Budget__c budget) {
        List<Time__c> timesToDelete = [SELECT Id FROM Time__c WHERE Project_Budget__c = :budget.Id];
        if (!timesToDelete.isEmpty()) {
            delete timesToDelete;
        }
    }

    // Method to create Time records for Project Role
    public static void createTimeRole(Project_Role__c role) {
        Id projectId = role.Project__c;
        Project__c project = [SELECT Start_Date__c, End_Date__c FROM Project__c WHERE Id = :projectId LIMIT 1];
        
        List<Time__c> timesToCreate = new List<Time__c>();

        for (Date dateIter = project.Start_Date__c; dateIter <= project.End_Date__c; dateIter = dateIter.addDays(1)) {
            Decimal plannedHours = isWeekend(dateIter) ? null : role.Default_hrs_weekday__c;

            Time__c newTime = new Time__c();
            newTime.Project_Role__c = role.Id;
            newTime.Project__c = projectId;
            newTime.Date__c = dateIter;
            newTime.Planned_hrs__c = plannedHours;
            newTime.Type__c = 'Planned';
            newTime.Category__c = 'Project Role';
            newTime.Key__c = generateKey(newTime);

            timesToCreate.add(newTime);
        }

        if (!timesToCreate.isEmpty()) {
            insert timesToCreate;
            createProjectRoleRollups(role, timesToCreate);
        }
    }

    // Method to delete Time records associated with a Project Role
    public static void deleteTimesForProjectRole(Project_Role__c role) {
        List<Time__c> timesToDelete = [SELECT Id FROM Time__c WHERE Project_Role__c = :role.Id];
        if (!timesToDelete.isEmpty()) {
            delete timesToDelete;
        }
    }

    // Placeholder method for Project Resource
    public static void createTimeResource(Project_Resource__c resource) {
        /* save for later */
    }

    // Placeholder method for Project Task
    public static void createTimeTask(Project_Task__c task) {
        /* save for later */
    }

    // Method to create rollups for Project Budget Time records
    private static void createProjectBudgetRollups(Project_Budget__c budget, List<Time__c> times) {
        List<Project_Budget_Rollup__c> rollupsToCreate = new List<Project_Budget_Rollup__c>();

        for (Time__c timeRecord : times) {
            Project_Budget_Rollup__c newRollup = new Project_Budget_Rollup__c();
            newRollup.Time__c = timeRecord.Id;
            newRollup.Project_Budget__c = budget.Id;
            newRollup.Budget_hrs__c = timeRecord.Budget_hrs__c;
            rollupsToCreate.add(newRollup);
        }

        if (!rollupsToCreate.isEmpty()) {
            insert rollupsToCreate;
        }
    }

    // Method to create rollups for Project Role Time records
    private static void createProjectRoleRollups(Project_Role__c role, List<Time__c> times) {
        List<Project_Role_Rollup__c> rollupsToCreate = new List<Project_Role_Rollup__c>();

        for (Time__c timeRecord : times) {
            Project_Role_Rollup__c newRollup = new Project_Role_Rollup__c();
            newRollup.Time__c = timeRecord.Id;
            newRollup.Project_Role__c = role.Id;
            newRollup.Planned_hrs__c = timeRecord.Planned_hrs__c;
            rollupsToCreate.add(newRollup);
        }

        if (!rollupsToCreate.isEmpty()) {
            insert rollupsToCreate;
        }
    }


    // Method to update rollup objects when a Time__c record is updated
    public static void updateRollupsForTime(Time__c timeRecord) {
        if (timeRecord.Project_Budget__c != null) {
            updateProjectBudgetRollup(timeRecord);
        } else if (timeRecord.Project_Role__c != null) {
            updateProjectRoleRollup(timeRecord);
        }
    }

    // Method to update Project_Budget_Rollup__c for a given Time__c record
    private static void updateProjectBudgetRollup(Time__c timeRecord) {
        Project_Budget_Rollup__c budgetRollup = [SELECT Id, Budget_hrs__c 
                                                 FROM Project_Budget_Rollup__c 
                                                 WHERE Time__c = :timeRecord.Id 
                                                 LIMIT 1];
        if (budgetRollup != null) {
            budgetRollup.Budget_hrs__c = timeRecord.Budget_hrs__c;
            update budgetRollup;
        }
    }

    // Method to update Project_Role_Rollup__c for a given Time__c record
    private static void updateProjectRoleRollup(Time__c timeRecord) {
        Project_Role_Rollup__c roleRollup = [SELECT Id, Planned_hrs__c 
                                             FROM Project_Role_Rollup__c 
                                             WHERE Time__c = :timeRecord.Id 
                                             LIMIT 1];
        if (roleRollup != null) {
            roleRollup.Planned_hrs__c = timeRecord.Planned_hrs__c;
            update roleRollup;
        }
    }


    // Helper method to check if a given date is a weekend
    private static Boolean isWeekend(Date dateValue) {
        Datetime dateTimeValue = Datetime.newInstance(dateValue.year(), dateValue.month(), dateValue.day());
        String dayOfWeek = dateTimeValue.format('EEEE');
        return dayOfWeek == 'Saturday' || dayOfWeek == 'Sunday';
    }

    // Helper method to generate a unique key for Time records
    private static String generateKey(Time__c timeRecord) {
        return String.valueOf(timeRecord.Date__c) + '.' +
               String.valueOf(timeRecord.Category__c) + '.' +
               String.valueOf(timeRecord.Type__c) + '.' +
               String.valueOf(timeRecord.Project__c) + '.' +
               String.valueOf(timeRecord.Project_Budget__c) + '.' +
               String.valueOf(timeRecord.Project_Role__c);
    }
}