objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Budget_hrs__c</fullName>
        <label>Budget (hrs)</label>
        <summarizedField>Project_Budget__c.Selected_Budget_hrs__c</summarizedField>
        <summaryForeignKey>Project_Budget__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

objects/Project_Budget__c.object
<CustomObject>
    <label>Project Budget</label>
    <nameField>
        <displayFormat>PBU-{00000000}</displayFormat>
        <label>Project Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Budget_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <inlineHelpText>8 character Nickname for this Budget.</inlineHelpText>
        <label>Nickname</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Budget_hrs__c</fullName>
        <formula>CASE(
    Type__c,
    &quot;Manual&quot;, Manual_Budget_hrs__c,
    &quot;Opportunity&quot;, Opportunity_Quantity_hrs__c,
    &quot;Opportunity Product&quot;, Opportunity_Product_Quantity_hrs__c,
    0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Time__c.object
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>TME-{00000000}</displayFormat>
        <label>Time</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Past__c</fullName>
        <formula>Date__c &lt; TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Past</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Today__c</fullName>
        <formula>Date__c == TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Today</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Future__c</fullName>
        <formula>Date__c &gt; TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Future</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_hrs__c</fullName>
        <label>Budget (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Weekday__c</fullName>
        <formula>!(WEEKDAY(Date__c) == 1 || WEEKDAY(Date__c) == 7)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Weekday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Planned_hrs__c</fullName>
        <label>Planned (hrs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Last_Week__c</fullName>
        <formula>WEEKDAY(Date__c) &gt;= 1 &amp;&amp; WEEKDAY(Date__c) &lt;= 7 &amp;&amp; Date__c &lt; TODAY() &amp;&amp; Date__c &gt;= (TODAY() - (7 - WEEKDAY(TODAY()) + 1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Last Week</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Next_Week__c</fullName>
        <formula>Date__c &gt; TODAY() &amp;&amp; Date__c &lt;= (TODAY() + 7)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Next Week</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_This_Week__c</fullName>
        <formula>Date__c &gt;= (TODAY() - WEEKDAY(TODAY()) + 1) &amp;&amp; Date__c &lt; (TODAY() + (8 - WEEKDAY(TODAY())))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is This Week</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_This_Year__c</fullName>
        <formula>YEAR(Date__c) = YEAR(TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is This Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Last_Month__c</fullName>
        <formula>MONTH(Date__c) = MONTH(TODAY()) - 1 &amp;&amp; YEAR(Date__c) = YEAR(TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Last Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Next_Month__c</fullName>
        <formula>MONTH(Date__c) = MONTH(TODAY()) + 1 &amp;&amp; YEAR(Date__c) = YEAR(TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Next Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_This_Month__c</fullName>
        <formula>MONTH(Date__c) = MONTH(TODAY()) &amp;&amp; YEAR(Date__c) = YEAR(TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is This Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Budget</label>
        <referenceTo>Project_Budget__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Future_and_Today__c</fullName>
        <formula>Date__c &gt;= TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Future and Today</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/ProjectTimesController.cls
public with sharing class ProjectTimesController {

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRecordsForType(String objectApiName, Id projectId) {
        String query = 'SELECT Id, Nickname__c FROM ' + objectApiName + ' WHERE Project__c = :projectId';
        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<Time__c> getTimeRecordsForType(String parentObjectApiName, Id parentRecordId) {
        //String fieldToQuery = (parentObjectApiName == 'Project_Budget__c') ? 'Budget_hrs__c' : 'Planned_hrs__c';
        //String fieldToQuery = '';
    
        String query = 'SELECT Id, Date__c, Budget_hrs__c, Planned_hrs__c, ' + 
                       'Is_Future__c, Is_Future_and_Today__c, Is_Last_Month__c, Is_Last_Week__c, ' +
                       'Is_Next_Month__c, Is_Next_Week__c, Is_Past__c, Is_This_Month__c, ' +
                       'Is_This_Week__c, Is_This_Year__c, Is_Today__c, Is_Weekday__c ' +
                       'FROM Time__c WHERE ' + parentObjectApiName + ' = :parentRecordId';
    
        List<Time__c> timeRecords = Database.query(query);
        return timeRecords;
    }
}